Updated openvpn helper

diff --git a/bin/vpn/openvpn_exec_helper b/bin/vpn/openvpn_exec_helper
--- a/bin/vpn/openvpn_exec_helper
+++ b/bin/vpn/openvpn_exec_helper
@@ -3,64 +3,80 @@
 set -u
 #set -x
 
-
 _help_exit() {
-    echo "Usage:\n$0 path_to_cfg_file mode [pass_file_name]"
+    echo "Usage:\n$0 mode full_path_to_file_ovpn [pass_file_name]"
     echo "Select mode: up|down"
     exit 1
 }
 
-[ $# -lt 2 ] && _help_exit
-VPN_CFG_FILE=$1
-MODE=$2
+[ $# -lt 1 ] && _help_exit
+MODE=$1
+CFG_FILE=$2
 auth_user_pass=${3:-}
 
-if [ "$(whoami)" != "$USER" ] || [ -z "$VPN_CFG_FILE" ]; then
+CFG_FILE=$(readlink -e "$CFG_FILE")
+CFG_DIR=$(dirname "$CFG_FILE")
+OVPN_FILE=$(basename "$CFG_FILE")
+
+LOG_FILE=/tmp/_w_ovpn_.log
+
+if [ "$(whoami)" != "$USER" ] || [ -z "$CFG_FILE" ]; then
   echo "You have to run this script as simple user!"
   echo "USER=$USER"
-  echo "VPN_CFG_FILE=$VPN_CFG_FILE"
+  echo "CFG_FILE=$CFG_FILE"
   exit 1
 fi
 
-VPN_CFG_FILE=$(readlink -e "$VPN_CFG_FILE")
-CFG_DIR=$(dirname "$VPN_CFG_FILE")
-CFG_NAME=$(basename "$VPN_CFG_FILE")
+MASK="openvpn --config"
 
-ids=$(pgrep -f "openvpn --config $CFG_NAME")
-
-cd ""
-start() {
-    if [ "$ids" != '' ]; then 
-        echo "VPN already started"
-        exit 1
-    fi
-    [ -n "$auth_user_pass" ] && OPT="--auth-user-pass $auth_user_pass"
-    cmd="sudo openvpn --config $CFG_NAME $OPT --"
-    echo "$cmd"
-    eval "$cmd" &
-    status=$?
-    echo "!!! Finish"
-    exit $status
+_ps(){
+    ids=$(pgrep -fa "$MASK")
+    echo -e "$ids"
 }
 
-stop() {
+_down() {
+    echo -e "\ndown ..."
+
+    ids=$(pgrep -fa "$MASK")
     if [ "$ids" = '' ]; then 
-        echo "VPN process not exist"
-        exit 1
+        echo "No VPN processes"
+        return 1
     fi
-    cmd="sudo pkill -f '$CFG_NAME'"
+
+    _ps
+    cmd="sudo pkill -f '$MASK'"
     echo "$cmd"
     eval "$cmd"
-    status=$?
-    echo "!!! Finish"
-    exit $status
+    sleep 1
 }
 
 
-cd "$CFG_DIR"
-[ "$MODE" = 'up' ] && start
-[ "$MODE" = 'down' ] && stop
-cd -
+_up() {
+    echo -e "\nup ..."
 
-_help_exit
+    if [ ! -f "$CFG_FILE" ]; then
+        echo "Can't find file ${CFG_FILE}"
+        exit 1
+    fi
 
+    ids=$(pgrep -fa "$MASK")
+    if [ "$ids" != '' ]; then 
+        echo "VPN was already started"
+        _down
+        sleep 1
+    fi
+
+    cd "$CFG_DIR"
+    [ -n "$auth_user_pass" ] && OPT="--auth-user-pass $auth_user_pass" || OPT=""
+    echo "" >> "$LOG_FILE"
+    (sudo openvpn --config $OVPN_FILE $OPT 2>&1 >> "$LOG_FILE") &
+}
+
+[ "$MODE" = 'up'   ] && _up
+[ "$MODE" = 'down' ] && _down
+
+echo -e "\nFinish !!!"
+
+_ps
+
+echo -e "\nLog: $LOG_FILE\n"
