Improved _clean_history

diff --git a/bin/fs/_clean_history b/bin/fs/_clean_history
--- a/bin/fs/_clean_history
+++ b/bin/fs/_clean_history
@@ -24,12 +24,14 @@ shift
 view_cmd="history | ag $@ '$re'"
 
 if [ "$mode" = 'v' ]; then
-    echo " $view_cmd"
+    echo -e "\n#Delete:\n $SCRIPT_NAME '$re' d $@"
+    echo -e "\n#Check:\n $view_cmd\n"
     exit $?
 fi
 
 if [ "$mode" = 'd' ]; then
-    echo " echo '';$view_cmd;echo '';for _i in \`$view_cmd | awk '{print \$1;}' | tr '*' ' ' | sort -rn\`; do history -d \$_i || echo \"Error: history -d \$_i\"; done;unset _i;$view_cmd && echo 'Check history' || echo 'Removed - Ok'"
+    check="echo -e \"\n $view_cmd\n\""
+    echo " $check;$view_cmd;echo '';read -p 'Press Enter for delete...';for _i in \`$view_cmd | awk '{print \$1;}' | tr '*' ' ' | sort -rn\`; do history -d \$_i || echo \"Error: history -d \$_i\"; done;unset _i;history -w;$view_cmd && echo 'Check history' || echo 'Removed - Ok';$check"
     exit $?
 fi
 
