Improved _clean_history

diff --git a/bin/fs/_clean_history b/bin/fs/_clean_history
--- a/bin/fs/_clean_history
+++ b/bin/fs/_clean_history
@@ -22,19 +22,17 @@ mode=${1:-v}
 shift
 
 view_cmd="history | ag $@ '$re'"
+if [ $mode != 'v' -a '' != 'd' ]; then
+    echo "Check mode: $mode"
+    print_help
+    exit 1
+fi
 
 if [ "$mode" = 'v' ]; then
-    echo -e "\n#Delete:\n $SCRIPT_NAME '$re' d $@"
-    echo -e "\n#Check:\n $view_cmd\n"
-    exit $?
+    echo -e "\n # Check only:\n $view_cmd"
 fi
 
-if [ "$mode" = 'd' ]; then
-    check="echo -e \"\n $view_cmd\n\""
-    echo " $check;$view_cmd;echo '';read -p 'Press Enter for delete...';for _i in \`$view_cmd | awk '{print \$1;}' | tr '*' ' ' | sort -rn\`; do history -d \$_i || echo \"Error: history -d \$_i\"; done;unset _i;history -w;$view_cmd && echo 'Check history' || echo 'Removed - Ok';$check"
-    exit $?
-fi
-
-echo "Check mode: $mode"
-print_help
-exit 1
+echo -e "\n #Delete:"
+check="echo -e \"\n $view_cmd\n\""
+echo " $check;$view_cmd;echo '';read -p 'Press Enter for delete...';for _i in \`$view_cmd | awk '{print \$1;}' | tr '*' ' ' | sort -rn\`; do history -d \$_i || echo \"Error: history -d \$_i\"; done;unset _i;history -w;$view_cmd && echo 'Check history' || echo 'Removed - Ok';$check"
+echo
