Update ksnip_install

diff --git a/bin/tools/ksnip_install b/bin/tools/ksnip_install
--- a/bin/tools/ksnip_install
+++ b/bin/tools/ksnip_install
@@ -13,43 +13,66 @@ fi
 
 ksnip_repo="https://github.com/ksnip/ksnip/releases"
 
-
+force_mode=0
 ksnip_fn=${1:-$last_version_deb}
+if [ "$ksnip_fn" = '-f' ]; then 
+    shift
+    ksnip_fn=${1:-$last_version_deb}
+    force_mode=1
+fi
 ksnip_vpath=${2:-continuous}
 
 echo "Try to download file ${ksnip_fn} from $ksnip_repo"
 
 tmp_dir=/tmp
 install_file="${tmp_dir}/${ksnip_fn}"
-
-cmd="wget -O '$install_file' '${ksnip_repo}/download/${ksnip_vpath}/${ksnip_fn}'"
-echo "$cmd"
-eval "$cmd"
+prev_install_file="${tmp_dir}/ksnip_prev_install.deb"
 
 _clean(){
     [ -e "$install_file" ] && rm -f "$install_file"
 }
 
+_check_diff() {
+    [ ! -e "$prev_install_file" ] && return 1
+    [ ! -e "$install_file" ] && return 1
+    diff -q "$install_file" "$prev_install_file"  > /dev/null
+    return $?
+}
+
+cmd="wget -O '$install_file' '${ksnip_repo}/download/${ksnip_vpath}/${ksnip_fn}'"
+echo "$cmd"
+eval "$cmd"
 if [ "$?" != 0 ]; then
-    echo "Can't download file: $ksnip_fn"
-    echo "Check: $ksnip_repo"
+    echo -e "\nCan't download file: $ksnip_fn"
+    echo -e "\nCheck: $ksnip_repo"
     _clean
     exit 1
 fi
 
 if [ ! -e "$install_file" ]; then
-    echo "File $install_file does not exists"
-    echo "Check: $ksnip_repo"
+    echo -e "\nFile $install_file does not exists"
+    echo -e "\nCheck: $ksnip_repo"
     _clean
     exit 1
 fi
 
 if [ -s "$install_file" ]; then
+    if [ "$force_mode" = '1' ]; then
+        [ -e "$prev_install_file" ] && rm "$prev_install_file"
+    fi
+    _check_diff
+    if [ $? -eq 0 ]; then
+        echo -e "\nFile $install_file was already installed\n"
+        ls -la1 "$install_file" "$prev_install_file"
+        echo -e "\nUse option -f as first parameter for force install"
+        exit 0
+    fi
     sudo dpkg -i "$install_file"
+    mv "$install_file" "$prev_install_file"
 else
-    echo "File $install_file has zero size"
-    echo $(ls -la "$install_file")
-    echo "Check: $ksnip_repo"
+    echo -e "\nFile $install_file has zero size"
+    ls -la1 "$install_file" "$prev_install_file"
+    echo -e "\nCheck: $ksnip_repo"
     _clean
     exit 1
 fi
